AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  suncoMiddleware

  Sample SAM Template for suncoMiddleware
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  MiddlewareApp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sunco-middleware/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        SuncoMiddleware:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hook
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MiddlewareApi:
    Description: "API Gateway endpoint URL for Prod stage for Sunco Middleware function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hook/"
  MiddlewareApp:
    Description: "Sunco Middleware Function ARN"
    Value: !GetAtt MiddlewareApp.Arn
  MiddlewareAppFunctionIamRole:
    Description: "Implicit IAM Role created for Sunco Middleware function"
    Value: !GetAtt MiddlewareAppRole.Arn